### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by OstojaOfficial** [Oleffa/LeagueAI#3]
I got these errors when I ran the Module

`Warning (from warnings module):
  File "..\object_detection\utils\visualization_utils.py", line 25
    import matplotlib; matplotlib.use('Agg')  # pylint: disable=multiple-statements
UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\idlelib\run.py", line 144, in main
    ret = method(*args, **kwargs)
  File "C:\Program Files\Python36\lib\idlelib\run.py", line 474, in runcode
    exec(code, self.locals)
  File "C:\tensorflow1\models\research\LeagueAI\LeagueAI.py", line 20, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\<name>\AppData\Roaming\Python\Python36\site-packages\matplotlib\pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "C:\Users\<name>\AppData\Roaming\Python\Python36\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()

Traceback (most recent call last):
  File "C:\tensorflow1\models\research\LeagueAI\LeagueAI.py", line 73, in <module>
    serialized_graph = fid.read()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 119, in read
    self._preread_check()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: LeagueAI_v3/frozen_inference_graph.pb : The system cannot find the path specified.

; No such process`

Can someone help me fix this?

**Comment by Oleffa** [comment]
Hi,

as far as I can tell, you used the LeagueAI.py file. This is unfortunately not tested as much because I used the jupyter notebook LeagueAI.ipynb to develop. I removed the matplotlib import since it is not used anywhere. So the warning about the matplotlib import should be fixed, and possibly also the first error. The second error says that you are missing the network trained to detect objects in League of Legends usually located in "./LeagueAI_v3/". Did you unpack the LeagueAI_v3.zip file? I will add this step to the instructions. This should hopefully fix your errors, if not try using the jupyter notebook and let me know!

Unfortunately I can't do more testing on the .py file until next month. However I plan to do some further work on this project in the upcoming months.

Best Regards.
