### ISSUE TITLE
can you provide your python virtualenv？

### ISSUE THREAD

**Issue by 14251104246** [Oleffa/LeagueAI#4]
- I run the LeagueAI , and then it throw an exception as flow.
- I don't know which version of MSS is correct.
````
2018-10-14 13:08:48.478820: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\182.4505.26\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\182.4505.26\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\182.4505.26\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\root\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\182.4505.26\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/root/studyProject/LeagueAI/LeagueAI.py", line 806, in <module>
    main_routine()
  File "C:/Users/root/studyProject/LeagueAI/LeagueAI.py", line 485, in main_routine
    sct.get_pixels(mon)
AttributeError: 'MSS' object has no attribute 'get_pixels'
```

**Comment by 14251104246** [comment]
Congratulations！I am successful to run it.
My python virtualenv is as flow：
```
absl-py==0.5.0
anaconda-client==1.7.2
appdirs==1.4.3
asn1crypto==0.24.0
astor==0.7.1
attrs==18.2.0
Automat==0.7.0
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
clyent==1.2.2
colorama==0.3.9
constantly==15.1.0
cryptography==2.3.1
cycler==0.10.0
Cython==0.28.5
decorator==4.3.0
entrypoints==0.2.3
gast==0.2.0
grpcio==1.15.0
h5py==2.8.0
html5lib==1.0.1
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
ipykernel==4.10.0
ipython==6.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.1
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.0
mistune==0.8.3
mkl-fft==1.0.6
mkl-random==1.0.1
mss==2.0.22
nb-anacondacloud==1.4.0
nb-conda==2.2.1
nb-conda-kernels==2.1.0
nbconvert==5.3.1
nbformat==4.4.0
nbpresent==3.0.2
notebook==5.6.0
numpy==1.15.2
olefile==0.46
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.4
Pillow==5.2.0
prometheus-client==0.3.1
prompt-toolkit==1.0.15
protobuf==3.6.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycparser==2.19
Pygments==2.2.0
PyHamcrest==1.9.0
pyOpenSSL==18.0.0
pyparsing==2.2.1
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
pywin32==223
pywinpty==0.5.4
PyYAML==3.13
pyzmq==17.1.2
requests==2.19.1
Send2Trash==1.5.0
service-identity==17.0.0
simplegeneric==0.8.1
six==1.11.0
tensorboard==1.11.0
tensorflow==1.11.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
tornado==5.1.1
traitlets==4.3.2
Twisted==18.7.0
urllib3==1.23
utils2==0.1.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
zope.interface==4.5.0

```
